# Generated by Django 4.1 on 2022-08-25 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0010_remove_veterinario_prestador_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.veterinario'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestador'),
        ),
    ]
