# Generated by Django 4.1 on 2022-08-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0007_pet_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nome_medicamento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_aplicacao", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clientes.pet"
                    ),
                ),
            ],
        ),
    ]
