# Generated by Django 4.1 on 2022-09-26 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anamneses", "0003_remove_anamneses_aplicacao"),
        ("aplicacoes", "0003_aplicacao_agendamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aplicacao",
            name="agendamento",
        ),
        migrations.AddField(
            model_name="aplicacao",
            name="anamneses",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="anamneses.anamneses",
            ),
        ),
    ]
