# Generated by Django 4.0.3 on 2022-06-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0005_alter_prestador_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
