# Generated by Django 4.0.3 on 2022-06-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0006_alter_veterinario_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
