# Generated by Django 4.1 on 2022-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0008_alter_prestador_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestador",
            name="status",
        ),
        migrations.AlterField(
            model_name="prestador",
            name="avatar",
            field=models.ImageField(
                blank=True,
                height_field=100,
                null=True,
                upload_to="user_avatar",
                width_field=100,
            ),
        ),
        migrations.AlterField(
            model_name="prestador",
            name="capa",
            field=models.ImageField(
                blank=True,
                height_field=1600,
                null=True,
                upload_to="user_background",
                width_field=200,
            ),
        ),
    ]
