# Generated by Django 4.1 on 2022-08-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0009_remove_prestador_status_alter_prestador_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veterinario",
            name="prestador",
        ),
        migrations.AlterField(
            model_name="veterinario",
            name="avatar",
            field=models.ImageField(
                blank=True,
                height_field=100,
                null=True,
                upload_to="user_avatar",
                width_field=100,
            ),
        ),
        migrations.AlterField(
            model_name="veterinario",
            name="capa",
            field=models.ImageField(
                blank=True,
                height_field=1600,
                null=True,
                upload_to="user_background",
                width_field=200,
            ),
        ),
        migrations.CreateModel(
            name="PrestadorVeterinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_vinculo", models.DateField(auto_now_add=True, null=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.prestador",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.veterinario",
                    ),
                ),
            ],
        ),
    ]
