# Generated by Django 4.0.3 on 2022-03-31 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('raca', models.CharField(blank=True, max_length=32, null=True)),
                ('idade_anos', models.IntegerField(blank=True, null=True)),
                ('idade_meses', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=30, null=True)),
                ('idCliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
