# Generated by Django 4.0.3 on 2022-04-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_pet_idcliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='idCliente',
            new_name='cliente',
        ),
    ]
