# Generated by Django 4.0.3 on 2022-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_pet_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tipo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
