version: '3'

services:
  db-medonvet:
    image: mysql
    volumes:
      - ./docker/provision/mysql/init-f:/docker-entrypoint-initdb.d
      - ./mysql-files:/var/lib/mysql-files
    environment:
    - MYSQL_ROOT_PASSWORD=ADMIN
    - MYSQL_DATABASE=db-medonvet
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password


