version: '3'

services:
  db-medonvet:
    image: mysql
    volumes:
      - ./docker/provision/mysql/init-f:/docker-entrypoint-initdb.d
      - ./docker/mysql-files:/var/lib/mysql-files
    environment:
    - MYSQL_ROOT_PASSWORD=ADMIN
    - MYSQL_DATABASE=db-medonvet
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  nosql-db-medonvet:
    image: mongo:latest
    volumes:
      - ./docker/mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  img-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@localhost:27017/
    depends_on:
    - nosql-db-medonvet



