# Generated by Django 4.1 on 2022-08-31 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0007_pet_tipo"),
        ("prestadores", "0010_remove_veterinario_prestador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioFuncionamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.TimeField(blank=True, null=True)),
                ("termino", models.TimeField(blank=True, null=True)),
                ("intervalo", models.IntegerField(blank=True, null=True)),
                ("domingo", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "segunda_feira",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "terca_feira",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "quarta_feira",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "quinta_feira",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "sexta_feira",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("sabado", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(blank=True, null=True)),
                ("horario_selecionado", models.TimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "funcionamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamento.horariofuncionamento",
                    ),
                ),
            ],
        ),
    ]
