# Generated by Django 4.1 on 2022-09-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="domingo",
            new_name="dia_0",
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="quarta_feira",
            new_name="dia_1",
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="quinta_feira",
            new_name="dia_2",
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="sabado",
            new_name="dia_3",
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="segunda_feira",
            new_name="dia_4",
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="sexta_feira",
            new_name="dia_5",
        ),
        migrations.RenameField(
            model_name="horariofuncionamento",
            old_name="terca_feira",
            new_name="dia_6",
        ),
    ]
