# Generated by Django 4.1 on 2022-09-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0002_rename_domingo_horariofuncionamento_dia_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horariofuncionamento",
            name="inicio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="horariofuncionamento",
            name="termino",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
