# Generated by Django 4.1 on 2022-09-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0002_servico_veterinario_alter_servico_prestador"),
        ("agendamento", "0003_alter_horariofuncionamento_inicio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servicos.servico",
            ),
        ),
    ]
