# Generated by Django 4.1 on 2022-09-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0010_remove_veterinario_prestador_and_more"),
        ("clientes", "0007_pet_tipo"),
        ("agendamento", "0005_remove_agendamento_funcionamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="pet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.pet",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="veterinario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="prestadores.veterinario",
            ),
        ),
    ]
