# Generated by Django 4.1 on 2022-09-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0006_agendamento_pet_alter_agendamento_veterinario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="horario_selecionado",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
