# Generated by Django 4.1 on 2022-09-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aplicacoes", "0002_aplicacao_data_reaplicacao_aplicacao_notificar"),
        ("agendamento", "0007_alter_agendamento_horario_selecionado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anamneses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "queixa_principal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "frequencia_cardiaca",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "frequencia_respiratoria",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("linfonodo", models.CharField(blank=True, max_length=100, null=True)),
                ("cor_mucosa", models.CharField(blank=True, max_length=100, null=True)),
                ("tpc", models.CharField(blank=True, max_length=100, null=True)),
                ("hidratacao", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamento.agendamento",
                    ),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicacoes.aplicacao",
                    ),
                ),
            ],
        ),
    ]
