# Generated by Django 4.1 on 2022-09-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anamneses", "0002_alter_anamneses_aplicacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anamneses",
            name="aplicacao",
        ),
    ]
