# Generated by Django 4.1 on 2022-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anamneses", "0003_remove_anamneses_aplicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anamneses",
            name="queixa_principal",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
