# Generated by Django 4.0.3 on 2022-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
