# Generated by Django 4.0.3 on 2022-04-07 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_resetpassword_data_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='data_solicitacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 18, 3, 5, 167847)),
        ),
    ]
